##
# @File: SignalList.srv
# @Date: 16 November 2019
# @Author: Ryan Jacobson
#
# @Brief
# This service will populate the GUI's list of signals
# 
# @signal_list
# List of all startable signals
##


---
gui_msgs/GuiData[] signal_list
